package com.lnkj.privateshop.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lnkj.privateshop.entity.ShopEmchatBean;

import com.lnkj.privateshop.greendao.ShopEmchatBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shopEmchatBeanDaoConfig;

    private final ShopEmchatBeanDao shopEmchatBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shopEmchatBeanDaoConfig = daoConfigMap.get(ShopEmchatBeanDao.class).clone();
        shopEmchatBeanDaoConfig.initIdentityScope(type);

        shopEmchatBeanDao = new ShopEmchatBeanDao(shopEmchatBeanDaoConfig, this);

        registerDao(ShopEmchatBean.class, shopEmchatBeanDao);
    }
    
    public void clear() {
        shopEmchatBeanDaoConfig.clearIdentityScope();
    }

    public ShopEmchatBeanDao getShopEmchatBeanDao() {
        return shopEmchatBeanDao;
    }

}
